# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1plc9jnD0kgFJ7ZvfkpA-blmAsiL5AEdG
"""

import matplotlib.pyplot as plt
import numpy as np
x=np.array([0,6])
y=np.array([0,250])
plt.plot(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array([3,5,9,7,9])
y=np.array([33,26,15,45,9])
plt.plot(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
y=np.array([7,9,1,6,3])
plt.plot(x,marker='+')
plt.show()

import matplotlib.pyplot as plt
import numpy as np
y=np.array([3,6,9,7])
plt.plot(y,marker='*',ms=60)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
y=np.array([9,4,6,1])
plt.plot(y,marker='*',ms=30,mec='r')
plt.show()